<?php

/** @noinspection GlobalVariableUsageInspection */
/** @noinspection PhpUndefinedConstantInspection */
/** @noinspection SpellCheckingInspection */

namespace Dotlines\GhooriSubscription\Tests;

use Carbon\Carbon;
use Dotenv\Dotenv;
use Dotlines\Ghoori\AccessTokenRequest;
use Dotlines\GhooriSubscription\CancelDetailsRequest;
use Exception;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\ConnectException;
use JsonException;
use PHPUnit\Framework\TestCase;

class CancelDetailsRequestTest extends TestCase
{
    protected $backupStaticAttributes = false;
    protected $runTestInSeparateProcess = false;

    public string $serverUrl = '';
    public string $tokenUrl = '';
    public string $username = '';
    public string $password = '';
    public int $clientID = 0;
    public string $clientSecret = '';

    public string $accessToken = "";
    public string $subscriptionUrl = "";
    public string $requestID = "";
    public string $package = "";
    public string $cycle = "";
    public string $start = "";
    public string $end = "";
    public string $userReturnUrl = "";
    public string $mobile = "";
    public string $email = "";
    public string $reference = "";

    public string $cancelRequestID = "";
    public string $cancelDetailsRequestUrl = "";

    /**
     * @throws JsonException
     */
    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Dotenv::createImmutable(__DIR__ . '\\..')->safeLoad();

        $this->serverUrl = (array_key_exists('GHOORI_SERVER_URL', $_ENV) ? (string)$_ENV['GHOORI_SERVER_URL'] : (string)getenv('GHOORI_SERVER_URL'));
        $this->tokenUrl = $this->serverUrl . '/oauth/token';
        $this->username = array_key_exists('GHOORI_USERNAME', $_ENV) ? (string)$_ENV['GHOORI_USERNAME'] : (string)getenv('GHOORI_USERNAME');
        $this->password = array_key_exists('GHOORI_PASSWORD', $_ENV) ? (string)$_ENV['GHOORI_PASSWORD'] : (string)getenv('GHOORI_PASSWORD');
        $this->clientID = array_key_exists('GHOORI_CLIENT_ID', $_ENV) ? (int)$_ENV['GHOORI_CLIENT_ID'] : (int)getenv('GHOORI_CLIENT_ID');
        $this->clientSecret = array_key_exists('GHOORI_CLIENT_SECRET', $_ENV) ? (string)$_ENV['GHOORI_CLIENT_SECRET'] : (string)getenv('GHOORI_CLIENT_SECRET');

        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, $this->clientID, $this->clientSecret);
        $tokenResponse = $accessTokenRequest->send();
        $this->accessToken = (string)$tokenResponse['access_token'];

        $this->subscriptionUrl = $this->serverUrl . '/api/v1.0/subscribe';
        $this->package = 'BBC_Janala_Weekly1';
        $this->cycle = 'WEEKLY'; //possible values: DAILY, WEEKLY, FIFTEEN_DAYS, MONTHLY, THIRTY_DAYS, NINETY_DAYS, ONE_EIGHTY_DAYS
        $this->start = Carbon::now()->format('Y-m-d');
        $this->end = Carbon::now()->addYear()->format('Y-m-d');
        $this->userReturnUrl = 'https://test-app.local';
        $this->mobile = ''; //optional
        $this->email = ''; //optional
        $this->reference = ''; //optional

        $this->cancelRequestID = '184'; // will come from cancel request
        $this->cancelDetailsRequestUrl = '';
    }

    /**
     * @test
     * @throws JsonException
     * if the subscription is cancelled run it_gives_error_on_already_canceled_subscription(), otherwise this
     */
    final public function it_can_fetch_subscription_cancel_id(): void
    {
        $this->cancelDetailsRequestUrl = $this->serverUrl . '/api/v1.0/subscription/cancel/' . $this->cancelRequestID; //replace SERVER_URL & id (cancel request id) with value
        $cancelDetailsRequest = CancelDetailsRequest::getInstance($this->cancelDetailsRequestUrl, $this->accessToken);
        $cancelDetailsRequestResponse = $cancelDetailsRequest->send();

        self::assertNotEmpty($cancelDetailsRequestResponse);
        self::assertArrayHasKey('id', $cancelDetailsRequestResponse, json_encode($cancelDetailsRequestResponse, JSON_THROW_ON_ERROR));
        self::assertArrayHasKey('subscriptionID', $cancelDetailsRequestResponse);
        self::assertArrayHasKey('requestID', $cancelDetailsRequestResponse);
        self::assertArrayHasKey('status', $cancelDetailsRequestResponse);
        self::assertEquals('00', $cancelDetailsRequestResponse['errorCode']);
        self::assertArrayHasKey('errorMessage', $cancelDetailsRequestResponse);

        self::assertNotEmpty($cancelDetailsRequestResponse['id']);
        self::assertNotEmpty($cancelDetailsRequestResponse['subscriptionID']);
        self::assertNotEmpty($cancelDetailsRequestResponse['requestID']);
        self::assertNotEmpty($cancelDetailsRequestResponse['status']);
    }

    /**
     * @test
     * @throws JsonException
     * @throws Exception
     */
    final public function it_gets_exception_with_empty_cancel_request_url(): void
    {
        $this->cancelDetailsRequestUrl = ""; //replace SERVER_URL & subscriptionID with value
        $cancelDetailsRequest = CancelDetailsRequest::getInstance($this->cancelDetailsRequestUrl, $this->accessToken);
        $this->expectException(Exception::class);
        $cancelDetailsRequest->send();
    }

    /**
     * @test
     * @throws Exception
     * @throws JsonException
     */
    final public function it_gives_exception_with_wrong_cancel_request_url(): void
    {
        $this->cancelDetailsRequestUrl = "wrong url"; //replace SERVER_URL & subscriptionID with value
        $cancelDetailsRequest = CancelDetailsRequest::getInstance($this->cancelDetailsRequestUrl, $this->accessToken);
        $this->expectException(ConnectException::class);
        $cancelDetailsRequest->send();
    }

    /**
     * @test
     * @throws JsonException
     * @throws JsonException
     */
    final public function it_gets_exception_with_invalid_cancelRequestID(): void
    {
        $this->cancelRequestID = "NA";
        $this->cancelDetailsRequestUrl = $this->serverUrl . '/api/v1.0/subscription/cancel/' . $this->cancelRequestID; //replace SERVER_URL & id (cancel request id) with value
        $cancelDetailsRequest = CancelDetailsRequest::getInstance($this->cancelDetailsRequestUrl, $this->accessToken);
        $this->expectException(ClientException::class);
        $cancelDetailsRequest->send();
    }
}
