<?php


namespace Dotlines\GhooriSubscription\Tests;

use Dotlines\GhooriSubscription\Models\NotificationResponse;
use PHPUnit\Framework\TestCase;


class NotificationResponseTest extends TestCase
{
    public string $recordID = "";
    public string $status = "";
    public string $timestamp = "";

    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->recordID = "Record1234";
        $this->status = "done";
        $this->timestamp = date("Y-m-d");
    }

    /**
     * @test
     */

    final public function it_can_construct_NotificationResponse_object(): void
    {
        $ResponseObj = new NotificationResponse($this->recordID ,$this->status,$this->timestamp);
        self::assertEquals("Dotlines\GhooriSubscription\Models\NotificationResponse", get_class($ResponseObj));
    }

    /**
     * @test
     * @throws \JsonException
     */

    final public function it_can_return_json_encoded_parameter_of_NotificationResponse_object(): void
    {
        $responseObj = new NotificationResponse($this->recordID ,$this->status,$this->timestamp);
        $responseResult = json_decode($responseObj->__toString()) ;

        self::assertObjectHasAttribute("recordID",$responseResult);
        self::assertObjectHasAttribute("status",$responseResult);
        self::assertObjectHasAttribute("timestamp",$responseResult);
        self::assertNotEmpty($responseResult);
        self::assertNotEmpty("recordID", $responseResult->recordID);
        self::assertNotEmpty("status", $responseResult->status);
        self::assertNotEmpty("timestamp", $responseResult->timestamp);
    }
}