<?php


namespace Dotlines\GhooriSubscription\Tests;

use Dotlines\GhooriSubscription\Models\Notification;
use PHPUnit\Framework\TestCase;


class NotificationTest extends TestCase
{
    public string $notificationID = "";
    public string $invoiceID = "";
    public string $type = "";
    public string $status = "";
    public string $subscriptionID = "";
    public string $paymentID = "";
    public string $timestamp = "";

    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->notificationID = "abc";
        $this->invoiceID = "abjdjww";
        $this->type = "newType";
        $this->status = "newStatus";
        $this->subscriptionID = "430";
        $this->paymentID = "32";
        $this->timestamp = date("Y-m-d");
    }

    /**
     * @test
     */

    final public function it_can_construct_Notification_object(): void
    {
        $notificationObj = new Notification($this->notificationID, $this->invoiceID, $this->type, $this->status, $this->subscriptionID, $this->paymentID, $this->timestamp);
        self::assertEquals("Dotlines\GhooriSubscription\Models\Notification", get_class($notificationObj));
    }

}