<?php

/** @noinspection GlobalVariableUsageInspection */
/** @noinspection SpellCheckingInspection */
/** @noinspection PhpComposerExtensionStubsInspection */
/** @noinspection PhpUndefinedConstantInspection */

namespace Dotlines\GhooriSubscription\Tests;

use Carbon\Carbon;
use Dotenv\Dotenv;
use Dotlines\Ghoori\AccessTokenRequest;
use Dotlines\GhooriSubscription\RequestStatusRequest;
use Exception;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\ConnectException;
use JsonException;
use PHPUnit\Framework\TestCase;

class RequestStatusRequestTest extends TestCase
{
    protected $backupStaticAttributes = false;
    protected $runTestInSeparateProcess = false;

    public string $serverUrl = '';
    public string $tokenUrl = '';
    public string $username = '';
    public string $password = '';
    public int $clientID = 0;
    public string $clientSecret = '';

    public string $accessToken = "";
    public string $subscriptionUrl = "";
    public string $requestID = "";
    public string $package = "";
    public string $cycle = "";
    public string $start = "";
    public string $end = "";
    public string $userReturnUrl = "";
    public string $mobile = "";
    public string $email = "";
    public string $reference = "";

    public string $invoiceID = "";
    public string $requestStatusRequestUrl = "";

    /**
     * @throws JsonException
     */
    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Dotenv::createImmutable(__DIR__ . '\\..')->safeLoad();

        $this->serverUrl = (array_key_exists('GHOORI_SERVER_URL', $_ENV) ? (string)$_ENV['GHOORI_SERVER_URL'] : (string)getenv('GHOORI_SERVER_URL'));
        $this->tokenUrl = $this->serverUrl . '/oauth/token';
        $this->username = array_key_exists('GHOORI_USERNAME', $_ENV) ? (string)$_ENV['GHOORI_USERNAME'] : (string)getenv('GHOORI_USERNAME');
        $this->password = array_key_exists('GHOORI_PASSWORD', $_ENV) ? (string)$_ENV['GHOORI_PASSWORD'] : (string)getenv('GHOORI_PASSWORD');
        $this->clientID = array_key_exists('GHOORI_CLIENT_ID', $_ENV) ? (int)$_ENV['GHOORI_CLIENT_ID'] : (int)getenv('GHOORI_CLIENT_ID');
        $this->clientSecret = array_key_exists('GHOORI_CLIENT_SECRET', $_ENV) ? (string)$_ENV['GHOORI_CLIENT_SECRET'] : (string)getenv('GHOORI_CLIENT_SECRET');

        $accessTokenRequest = AccessTokenRequest::getInstance($this->tokenUrl, $this->username, $this->password, $this->clientID, $this->clientSecret);
        $tokenResponse = $accessTokenRequest->send();
        $this->accessToken = (string)$tokenResponse['access_token'];
        $this->subscriptionUrl = $this->serverUrl . '/api/v1.0/subscribe';
        $this->package = 'BBC_Janala_Weekly1';
        $this->cycle = 'WEEKLY'; //possible values: DAILY, WEEKLY, FIFTEEN_DAYS, MONTHLY, THIRTY_DAYS, NINETY_DAYS, ONE_EIGHTY_DAYS
        $this->start = Carbon::now()->format('Y-m-d');
        $this->end = Carbon::now()->addYear()->format('Y-m-d');
        $this->userReturnUrl = 'https://test-app.local';
        $this->mobile = ''; //optional
        $this->email = ''; //optional
        $this->reference = ''; //optional

        $this->invoiceID = "QTCFB934BBA3C0";    //will come from subscription charge request
        $this->requestStatusRequestUrl = '';
    }

    /**
     * @test
     * @throws JsonException
     */
    final public function it_can_fetch_request_status_invoiceID(): void
    {
        $this->requestStatusRequestUrl = $this->serverUrl . '/api/v1.0/subscribe/' . $this->invoiceID . '/status'; //replace SERVER_URL & invoiceID with value
        $requestStatusRequest = RequestStatusRequest::getInstance($this->requestStatusRequestUrl, $this->accessToken);
        $requestStatusRequestResponse = $requestStatusRequest->send();

        self::assertNotEmpty($requestStatusRequestResponse);
        self::assertArrayHasKey('invoiceID', $requestStatusRequestResponse, json_encode($requestStatusRequestResponse, JSON_THROW_ON_ERROR));
        self::assertArrayHasKey('status', $requestStatusRequestResponse);
        self::assertArrayHasKey('subscriptionID', $requestStatusRequestResponse);
        self::assertArrayHasKey('createdAt', $requestStatusRequestResponse);
        self::assertEquals('00', $requestStatusRequestResponse['errorCode']);
        self::assertArrayHasKey('errorMessage', $requestStatusRequestResponse);

        self::assertNotEmpty($requestStatusRequestResponse['invoiceID']);
        self::assertNotEmpty($requestStatusRequestResponse['status']);
        self::assertNotEmpty($requestStatusRequestResponse['subscriptionID']);
        self::assertNotEmpty($requestStatusRequestResponse['createdAt']);
    }

    /**
     * @test
     * @throws JsonException
     * @throws Exception
     */
    final public function it_gets_exception_with_empty_request_status_request_url(): void
    {
        $this->requestID = 'test-app-' . random_int(111111, 999999);
        $this->requestStatusRequestUrl = "";
        $requestStatusRequest = RequestStatusRequest::getInstance($this->requestStatusRequestUrl, $this->accessToken);
        $this->expectException(Exception::class);
        $requestStatusRequest->send();
    }

    /**
     * @test
     * @throws Exception
     */
    final public function it_gets_exception_with_invalid_request_status_request_url(): void
    {
        $this->requestID = 'test-app-' . random_int(111111, 999999);
        $this->requestStatusRequestUrl = "sdsadsasa";
        $requestStatusRequest = RequestStatusRequest::getInstance($this->requestStatusRequestUrl, $this->accessToken);
        $this->expectException(ConnectException::class);
        $requestStatusRequest->send();
    }

    /**
     * @test
     * @throws Exception
     */
    final public function it_gets_exception_with_empty_invoiceID(): void
    {
        $this->requestID = 'test-app-' . random_int(111111, 999999);
        $this->invoiceID = "";
        $this->requestStatusRequestUrl = $this->serverUrl . '/api/v1.0/subscribe/' . $this->invoiceID . '/status'; //replace SERVER_URL & invoiceID with value
        $requestStatusRequest = RequestStatusRequest::getInstance($this->requestStatusRequestUrl, $this->accessToken);
        $this->expectException(ClientException::class);
        $requestStatusRequest->send();
    }
}
